services:
  postgres:
    image: postgres:17.5
    restart: unless-stopped
    container_name: hono-todos
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sarika098
      POSTGRES_DB: todos